apiVersion: v2
name: masscan-exporter
description: A simple deployment of masscan-exporter.
type: application
version: 0.6.4 # x-release-please-version
# renovate: image=ghcr.io/mikemrm/masscan-exporter
appVersion: v0.6.4 # x-release-please-version
sources:
  - https://github.com/mikemrm/masscan-exporter
dependencies:
  - name: common
    repository: 'oci://registry-1.docker.io/bitnamicharts'
    version: '2.31.4'
