{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.names.fullname" $ | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 8 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
  endpoints:
    - port: http
{{- end }}
